### ISSUE TITLE
:bug: `mdformat-pyproject` not running properly

### ISSUE THREAD

**Issue by miloth** [jorenham/scipy-stubs#261]
I found the following issue while investigating the task-runners. Running `mdformat . --check` will print files in `.venv` and `.tox`, even though there are settings to exclude them:
```toml
[tool.mdformat]
end_of_line = "lf"
exclude = [".tox/**", ".venv/**", "**/*.m[!d]", "**/*.[!m]d"]
```

This is due to the `mdformat-pyproject` plugin.
